# http://gohugo.io/getting-started/configuration/#yaml-configuration

baseURL: http://keithmo.me/
title: Haunted Hovel - 闹鬼小屋
copyright: Copyright &copy; 2016-2018 - Keith Mo

disqusShortname: keithmo  # Disqus shortname
googleAnalytics: UA-81240089-1  # Google Analytics ID

defaultContentLanguage: zh-cn
#defaultContentLanguageInSubdir: false
hasCJKLanguage: true
languageCode: zh-cn

summaryLength: 50
enableEmoji: true
metaDataFormat: yaml

paginate: 10
paginatePath: page

# https://gohugo.io/content-management/urls/#canonicalization
disablePathToLower: true
permalinks:
  post: /:sections/:year/:month/:day/:slug
  guide: /:sections/:year/:month/:day/:slug

# http://gohugo.io/content-management/taxonomies/
taxonomies:
  category: categories
  tag: tags
  series: series

# https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
# https://help.farbox.com/pygments.html
pygmentsStyle: friendly  # {monokai | friendly | vs | autumn | ...}
#pygmentsOptions: "linenos=inline"  # {inline | table}

theme: kiera
#https://themes.gohugo.io/hugo-kiera/

# site variables:
# http://gohugo.io/variables/site/

author:
  name: Keith Mo       # Author name
  github: keithmork     # Github username
  #gitlab:     # Gitlab username
  #linkedin:   # LinkedIn username
  #facebook:   # Facebook username
  #twitter:    # Twitter username
  #instagram:  # Instagram username

params:
  tagline: 本站采用 <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用(BY-NC) 4.0 国际许可协议</a> 进行许可。


# https://gohugo.io/content-management/related/#configure-related-content
related:
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold: 80
  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer: false
  # Will lower case keywords in both queries and in the indexes.
  toLower: false
  indices:
  - name: keywords
    weight: 150
  - name: author
    toLower: true
    weight: 30
  - name: tags
    weight: 100
  - name: date
    weight: 10
    pattern: 2017
