#!/bin/bash

push_to_github=${1:-true}

if [[ -d public ]]; then
    GLOBIGNORE=*.git:*CNAME:*google31f388d9bc251ee9.html:*robots.txt
    rm -rf -v public/*
fi

hugo

if [[ "${push_to_github}" == "true" ]]; then
    cd public
    git add -A
    git commit -m 'new publish'
    git push
fi
