#!/bin/bash

push_to_github=${1:-false}

if [[ -d public ]]; then
    GLOBIGNORE=*.git
    rm -rf -v public/*
fi

hugo

if [[ "${push_to_github}" == "true" ]]; then
    cd public
    git add -A
    git commit -m 'new publish'
    git push
fi
